name: Composer 2 PSR Missing

on:
    pull_request: null

jobs:
    composer_2_psr_missing:
        name: ${{ matrix.actions.name }}
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.4

            -   run: composer self-update --2

            -   run: composer install --ansi

            -   run: vendor/bin/ecs
