name: Unit Tests

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    unit_tests:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: ['7.2', '7.3', '7.4']

        name: PHP ${{ matrix.php }} tests
        steps:
            -   uses: actions/checkout@v2

            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none
                    tools: composer:v1

            -   run: composer install --no-progress
            -   run: vendor/bin/phpunit --testsuite unit
